### ISSUE TITLE
Evaluate data with Google Sheets: a career in data analytics

### ISSUE THREAD

**Issue by ZacheeNiyokwizera** [CodeYourFuture/curriculum#802]
https://applieddigitalskills.withgoogle.com/c/college-and-continuing-education/en/try-a-career-in-data-analytics/overview.html

This is Step 2 of new ITD

#Tasks

- [x] Take the course
- [x] Write simple, short instructions for the applicants in B1 English
- [x] Upload as step 2 of new course in Staging

# Example below

### Instructions:
[Evaluate data with Google Sheets](https://applieddigitalskills.withgoogle.com/c/college-and-continuing-education/en/try-a-career-in-data-analytics/overview.html)

[This short course from Google](https://applieddigitalskills.withgoogle.com/c/college-and-continuing-education/en/try-a-career-in-data-analytics/overview.html) will teach you how to analyse and visualise data in Google Sheets. It is suitable for beginners. Come to CYF workshops to get help and to work with other applicants on your project. If you do not have a computer, [find your nearest free online centre](https://www.onlinecentresnetwork.org/ournetwork/find-centre#/map).

Complete the course and share a link to the final spreadsheet you made.  You can move on to the next step as soon as you have shared the link. You don't need to wait.

#### Personalise your URLs

Before you share your link with your mentors, edit your Google Spreadsheet name to include your name. It can just be your given name or your family name if you prefer. 

###Settings 
Show Image Upload: No
Show Motivational Letter: No
Show Submit Url: Yes
Is optional: No
Acceptance Criteria:
I have shared a link to my spreadsheet 
My spreadsheet includes my name in the title
My spreadsheet visualises the song data as ETC ETC BE VERY CLEAR AND SIMPLE

**Comment by Ara225** [comment]
I've done this now :)
